# -*- coding: utf-8 -*-
"""Random_forest_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQzsWToaZIMPyzB-RfMhLcf9kZU22Q9A

# Random Forest Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
Y = dataset.iloc[:, -1].values

"""## Training the Random Forest Regression model on the whole dataset"""

from sklearn.ensemble import RandomForestRegressor
# The n_estimators parameter specifies the number of decision trees to be used 
# in the random forest, and the random_state parameter is used to ensure 
# reproducibility of the results
regressor = RandomForestRegressor(n_estimators=10, random_state=1)
regressor.fit(X, Y)

"""## Predicting a new result"""

regressor.predict([[6.5]])

"""## Visualising the Random Forest Regression results (higher resolution)"""

X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, Y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Random forest regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()