# -*- coding: utf-8 -*-
"""Decision_tree_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MS3pvuGB1jgcMpZaIkXlJ7Qt-krTqcso

# Decision Tree Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

data = pd.read_csv("Position_Salaries.csv")
X = data.iloc[:, 1:-1].values
Y = data.iloc[:, -1].values

print(X)

Y = Y.reshape(len(Y), 1)
print(Y)

"""## Training the Decision Tree Regression model on the whole dataset"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 1)
regressor.fit(X, Y)

"""## Predicting a new result"""

regressor.predict([[6.5]])

"""## Visualising the Decision Tree Regression results (higher resolution)"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, Y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Decision Tree Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()